name: orbits
version: "0.4.0.1"
synopsis: Types and functions for Kepler orbits.
category: Physics
author: Ellie Hermaszewska
maintainer: Ellie Hermaszewska <keep.it.real@monoid.al>
copyright: 2020 Ellie Hermaszewska
github: expipiplus1/orbits
extra-source-files:
- .gitignore
- readme.md
- default.nix
- changelog.md

library:
  source-dirs: src
  other-modules:
    Data.Metrology.Extra
  dependencies:
  - ad         >= 4.3.2
  - base       >= 4.8 && < 5
  - exact-real >= 0.12
  - lens
  - linear
  - units
  - units-defs >= 2.2

ghc-options: -Wall -O2

default-extensions:
  DataKinds
  FlexibleContexts
  GeneralizedNewtypeDeriving
  LambdaCase
  QuasiQuotes
  ScopedTypeVariables
  TemplateHaskell
  TypeApplications
  TypeFamilies
  TypeOperators
  ViewPatterns

tests:
  test:
    main: Test.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
    dependencies:
      - QuickCheck
      - ad
      - base
      - checkers
      - exact-real
      - lens
      - linear
      - orbits
      - random
      - tagged
      - tasty
      - tasty-quickcheck
      - tasty-th
      - units
      - units-defs

  doctests:
    main: Doctests.hs
    other-modules: ""
    source-dirs:
      - test/doctest
    dependencies:
      - base
      - doctest

custom-setup:
 dependencies:
   - base
   - Cabal
   - cabal-doctest >= 1 && <1.1
